version: '3.9'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "5001:8000"
    environment:
      - APP_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/user_db
    depends_on:
      - postgres

  playlist-service:
    build:
      context: ./playlist-service
    ports:
      - "5002:8000"
    environment:
      - APP_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/playlist_db
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=5001
    depends_on:
      - postgres
      - user-service

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
